apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pytorch-image-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18, pipelines.kubeflow.org/pipeline_compilation_time: '2023-01-03T19:31:39.007695',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "training mnist data from
      minio in docker image", "name": "pytorch image pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18}
spec:
  entrypoint: pytorch-image-pipeline
  templates:
  - name: pytorch-data-upload
    container:
      command: [python, data.py]
      image: kimkihoon0515/pytorch-data
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: pytorch-image-pipeline
    dag:
      tasks:
      - {name: pytorch-data-upload, template: pytorch-data-upload}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
