apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
  creationTimestamp: "2023-01-01T11:16:55Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: notebook-volume
  namespace: kubeflow-user-example-com
  resourceVersion: "3229073"
  uid: e494fd85-e2b2-42ba-bbaf-d2c0c944880a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-e494fd85-e2b2-42ba-bbaf-d2c0c944880a
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
