apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pytorch-image-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18, pipelines.kubeflow.org/pipeline_compilation_time: '2023-01-10T09:39:16.919373',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "training mnist data from
      minio in docker image", "name": "pytorch image pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18}
spec:
  entrypoint: pytorch-image-pipeline
  templates:
  - name: java-app
    container:
      command: [java, Hello]
      image: kimkihoon0515/java-docker-app
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: pytorch-data-upload
    container:
      args: [--download_root, /home/jovyan]
      command: [python, data.py]
      image: kimkihoon0515/pvc-data
      volumeMounts:
      - {mountPath: /mnt/pipeline, name: pipeline}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pipeline
      persistentVolumeClaim: {claimName: kfp-pvc}
  - name: pytorch-image-pipeline
    dag:
      tasks:
      - name: java-app
        template: java-app
        dependencies: [pytorch-mnist-train]
      - {name: pytorch-data-upload, template: pytorch-data-upload}
      - name: pytorch-mnist-train
        template: pytorch-mnist-train
        dependencies: [pytorch-data-upload]
  - name: pytorch-mnist-train
    container:
      args: [--mount_path, /home/jovyan, --epochs, '3']
      command: [python, train.py]
      image: kimkihoon0515/pvc-train
      volumeMounts:
      - {mountPath: /mnt/pipeline, name: pipeline}
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /home/jovyan/mlpipeline-metrics.json}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pipeline
      persistentVolumeClaim: {claimName: kfp-pvc}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
